version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: solitude-postgres
    restart: unless-stopped
    ports:
      - '15432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: solitude-redis
    restart: unless-stopped
    ports:
      - '${REDIS_PORT}:6379'

  backend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: solitude-backend-dev
    restart: unless-stopped
    ports:
      - '${APP_PORT}:8080'
    depends_on:
      - postgres
      - redis
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: 5432
      REDIS_PORT: ${REDIS_PORT}
      APP_PORT: ${APP_PORT}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - ./:/app:delegated
      - /app/node_modules
      - ./yarn.lock:/app/yarn.lock:ro
    command: yarn run start:dev
volumes:
  pgdata:
