version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: quizzerhub-postgres
    restart: unless-stopped
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: quizzerhub-redis
    restart: unless-stopped
    ports:
      - '${REDIS_PORT}:6379'

  backend-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: quizzerhub-core-backend:latest
    container_name: quizzerhub-backend-prod
    restart: unless-stopped
    ports:
      - '${APP_PORT}:8080'
    depends_on:
      - postgres
      - redis
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      REDIS_PORT: ${REDIS_PORT}
      APP_PORT: ${APP_PORT}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASSWORD: ${MAIL_PASSWORD}

volumes:
  pgdata:
